### ISSUE TITLE
Create template to confirm account on email

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#129]
![Screenshot from 2019-10-08 18-25-45](https://user-images.githubusercontent.com/6358755/66434544-28abff80-e9f9-11e9-9054-56687690dba4.png)

**Comment by moisesgui** [comment]
i can do this!

**Comment by eerison** [comment]
Hey @edenilsonfe gogogoggo to do it :)

**Comment by edenilsonfe** [comment]
I'll do

**Comment by eerison** [comment]
Hey @edenilsonfe you can use this site as example: 

https://reallygoodemails.com/categories/confirmation/

**Comment by moisesgui** [comment]
make your name @edenilsonfe. kkkk

**Comment by eerison** [comment]
anyone?
