### ISSUE TITLE
Improve template register page

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#155]
Link page: https://www.myprofile.pro/pt_BR/register/

![Screenshot from 2019-10-25 10-37-38](https://user-images.githubusercontent.com/6358755/67575712-876cbb00-f713-11e9-807a-1fba21ee1f6c.png)

**Comment by edenilsonfe** [comment]
I'll update this page. What do you think about this layout?
![register_page](https://user-images.githubusercontent.com/10874292/67575960-019d3f80-f714-11e9-8170-d8cfb8564b7e.jpeg)

**Comment by eerison** [comment]
Great!!

just change the background and move the submit button to right 

Thanks @edenilsonfe
