### ISSUE TITLE
Add a label/identification to mark a field as required

### ISSUE THREAD

**Issue by edenilsonfe** [eerison/myprofile#256]

**Comment by yesidays** [comment]
Hello @eerison can I do this issue?

**Comment by eerison** [comment]
Hi @yesidays 

Yeah of course ☺️
But If you never used twig, I suggest you get this one first: https://github.com/eerison/myprofile/issues/268

Because those fields are added dynamically on page.

But if you wish start this issue no worries.

**Comment by yesidays** [comment]
Thanks @eerison, sure :D i prefer to start with the other, thanks

**Comment by eerison** [comment]
Perfect, @yesidays could you drop some message here #268, just to sign that issue for you?
