### ISSUE TITLE
Removing bootstrap from error pages

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#270]
Today there are those error pages

- [403](http://localhost:8000/index.php/_error/403)
- [404](http://localhost:8000/index.php/_error/404)
- [500](http://localhost:8000/index.php/_error/500)
- [Generic error page](http://localhost:8000/index.php/_error/430)

and we need to remove bootstrap to add [bulma.io](https://bulma.io/), could be really good create pages with a different layout!
you can see [index](https://github.com/eerison/myprofile/blob/master/templates/site/index.html.twig) page to know how to add bulma in twig page. 

But basically to import bulma.io you just need to change this "stylesheets" like this
https://github.com/eerison/myprofile/blob/160754d36584457ed075a89276096e2e8635cc71/templates/site/index.html.twig#L5

you can see those pages in `templates/bundles/TwigBundle/Exception`

expected pages:

![errors-page](https://user-images.githubusercontent.com/6358755/97047584-84e8af80-1579-11eb-8036-f9d36e0e2cd5.png)
 please change `green` to `dark` colours (in the project it's the `is-primary`)

**Comment by TomerPacific** [comment]
@eerison , do you still need help with this issue?

**Comment by eerison** [comment]
Yes @TomerPacific

**Comment by eerison** [comment]
Do you want do that?

**Comment by TomerPacific** [comment]
@eerison - yes, I'd like to help. Just so we are on the same page, this issue is to remove bootstrap from the pages you mentioned and also to add bulma? Or just the removal of bootstrap?

**Comment by eerison** [comment]
Yes @TomerPacific remove bootstrap and add bulma.io , and I really appreciate if you can improve the  layout of error pages.

**Comment by TomerPacific** [comment]
@eerison , I am having trouble installing make on my PC (Windows10). Tried various solutions, but have not succeeded.

Looking at the error templates, I see that the usage of bootstrap's grid system is prevalent. Do you want me to remove any keyword associated with bootstrap? And also replace this:

```
{% block stylesheets %}
    {{ encore_entry_link_tags('exception') }}
{% endblock %}
```

to this:

```
{% block stylesheets %}
     {{ encore_entry_link_tags('web-site') }}
{% endblock %}
```

**Comment by eerison** [comment]
Hi @TomerPacific 

are you using docker right?

maybe you need to run this

```sh
docker-compose up -d  --remove-orphans
docker-compose exec php make init or docker-compose exec php $(MAKE) init
docker-compose run --rm client make yarn
```

and about styles, you can't just change `exception` to `web-site` , you need to change html/tag's class becuase now we're using bootstrap's tags, if you just change it'll broken the page styles...

For you finish this task you need to try to run this project locally :/, But if you're using docker it should be fine, if not please put your error, or just put a messa in [gitter](https://gitter.im/myprofile_pro/Lobby?source=orgpage)

**Comment by TomerPacific** [comment]
@eerison , thanks for the reply. Like I stated in my previous comment:

_Do you want me to remove any keyword associated with bootstrap? And also replace this..._

I figured there was a need to remove the bootstrap classes.

I don't have experience with docker and your README.md file does not state how to use it, so I tried to install make on my Windows machine.

If you have instructions on how I can use docker, that could be helpful.

**Comment by eerison** [comment]
Hi @TomerPacific did you try this: https://docs.docker.com/docker-for-windows/install/

I guess, you just need to install like this docker docs and It should work ...

after install docker try to run this command `docker -v && docker-compose -v` you should get a output like this

```
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.25.5, build 8a1c60f6
```

if you see this, maybe you just need to run those commands 

```
docker-compose up -d  --remove-orphans
docker-compose exec php make init or docker-compose exec php $(MAKE) init
docker-compose run --rm client make yarn
```

**Comment by TomerPacific** [comment]
@eerison , thanks for your help. I was able to run the commands with some alterations to make them work, but I am having an error when I got to http://localhost:8000/. I think it would be best at this time to assign this issue to someone else. Sorry for wasting your time.

**Comment by eerison** [comment]
Hi @TomerPacific no worries, would you like to share a screenshot with error?

**Comment by ibonkonesa** [comment]
Is it this still open?

**Comment by eerison** [comment]
Yes @ibonkonesa fell free to contribute with the project :partying_face:
