### ISSUE TITLE
Create a new login page

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#271]
create a [login](http://www.myprofile.pro/en/login) page similar [register](https://www.myprofile.pro/en/login) page

register files
 - [register](templates/bundles/FOSUserBundle/Registration/register.html.twig)
 - [content](templates/bundles/FOSUserBundle/Registration/register_content.html.twig)

login files
 - [login](templates/bundles/FOSUserBundle/Security/login_content.html.twig)
 - [content](templates/bundles/FOSUserBundle/Security/login_content.html.twig)

**Comment by sourcefactory-at** [comment]
As discussed in #269 I'll try to create one with bulma that looks more like the registration page.

**Comment by sourcefactory-at** [comment]
I just created MR #274 with screenshots. Is this somehow what you expected?
