### ISSUE TITLE
Remove bootstrap from profile page

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#272]
Well this issue is really important to remove bootstrap and jquery from the project

basically need to do the same layout (but can change colours like home page) for [profile](https://www.myprofile.pro/eerison) page

you can see those files here: `templates/default`, the ideia is use only bulma for this page and maybe few JS lines.

![Screenshot from 2020-10-03 10-01-36](https://user-images.githubusercontent.com/6358755/94986484-7f421000-055f-11eb-8ffc-5478783a02ba.png)

**Comment by sourcefactory-at** [comment]
It seems there is already most if it done in bulma and not much boostrap left. I can take over this but it could take a few days.

**Comment by eerison** [comment]
Hi @sourcefactory-at any news?

**Comment by sourcefactory-at** [comment]
Sorry, busy with unexpected client project work.

It's nearly ready but there are problems with the zindex for the user image on the right and that bulma has no dropdown button for the pdf download. I think latest on monday it should be ready.

**Comment by eerison** [comment]
You can change this drop down for button group big it's better for you

**Comment by sourcefactory-at** [comment]
Thanks, I got them working by adding some css and js to reproduce bootstraps behaviour.

You can find the changes in #285, I hope it works for you as expected.
