### ISSUE TITLE
remove jquery, css and js not used anymore

### ISSUE THREAD

**Issue by eerison** [eerison/myprofile#287]

**Comment by eerison** [comment]
#183

**Comment by eerison** [comment]
![Screenshot from 2020-11-05 10-31-02](https://user-images.githubusercontent.com/6358755/98223242-24327d00-1f52-11eb-941f-e1fe827be037.png)
![Screenshot from 2020-11-05 10-30-17](https://user-images.githubusercontent.com/6358755/98223246-2563aa00-1f52-11eb-8266-0346beb3c6dc.png)

**Comment by moisesgui** [comment]
Remove and replace with another language or just remove unused commando and lines?

I think I can do this too !!

**Comment by eerison** [comment]
Hey @moisesgui 

for now, we need to use `Jquery`, because some part of this [page](https://myprofile.pro/eerison) use Jquery, we need to see away to keep this working without jquery  

look here

https://github.com/eerison/myprofile/blob/2e3797d3fe79d0ebc178fc0799ee6a925acf8757/webpack.config.js#L36-L43

and here too

https://github.com/eerison/myprofile/tree/master/assets/js

there are jquery files and other JS that don't need to be in the project

**Comment by moisesgui** [comment]
understand

**Comment by eerison** [comment]
well it'll be completely removed in the new release.
